spring.application.name=LostAndFoundCampusSystem
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/lost_and_found
spring.datasource.username=root
spring.datasource.password=Shashini123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


